<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="39" passed="28" failed="11" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-02-06T13:00:58Z" name="Default suite" finished-at="2019-02-06T13:04:29Z" duration-ms="210487">
    <groups>
    </groups>
    <test started-at="2019-02-06T13:00:58Z" name="Default test" finished-at="2019-02-06T13:04:29Z" duration-ms="210487">
      <class name="src.Wfs_automation">
        <test-method signature="browserlaunch()[pri:1, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:00:58Z" name="browserlaunch" finished-at="2019-02-06T13:01:38Z" duration-ms="39547" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserlaunch -->
        <test-method signature="checkvalidation()[pri:2, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:01:38Z" name="checkvalidation" finished-at="2019-02-06T13:01:39Z" duration-ms="1744" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkvalidation -->
        <test-method signature="companyname()[pri:3, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:01:39Z" name="companyname" finished-at="2019-02-06T13:01:42Z" duration-ms="2488" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- companyname -->
        <test-method signature="lastnamespecialchar()[pri:4, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:01:42Z" name="lastnamespecialchar" finished-at="2019-02-06T13:01:45Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2580" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [special symbols are not allowed.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [special symbols are not allowed.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at src.Wfs_automation.lastnamespecialchar(Wfs_automation.java:118)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastnamespecialchar -->
        <test-method signature="lastnameinteger()[pri:5, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:01:45Z" name="lastnameinteger" finished-at="2019-02-06T13:01:47Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2565" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [Integers are not allowed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [Integers are not allowed]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at src.Wfs_automation.lastnameinteger(Wfs_automation.java:139)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastnameinteger -->
        <test-method signature="lastnamereal()[pri:6, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:01:47Z" name="lastnamereal" finished-at="2019-02-06T13:01:49Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2290" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastnamereal -->
        <test-method signature="firstnamespecialchar()[pri:7, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:01:49Z" name="firstnamespecialchar" finished-at="2019-02-06T13:01:52Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2583" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [special symbols are not allowed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [special symbols are not allowed]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at src.Wfs_automation.firstnamespecialchar(Wfs_automation.java:177)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstnamespecialchar -->
        <test-method signature="firstnameinteger()[pri:8, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:01:52Z" name="firstnameinteger" finished-at="2019-02-06T13:01:55Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2528" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [Integers are not allowed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [Integers are not allowed]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at src.Wfs_automation.firstnameinteger(Wfs_automation.java:197)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstnameinteger -->
        <test-method signature="firstnamereal()[pri:9, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:01:55Z" name="firstnamereal" finished-at="2019-02-06T13:01:57Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2327" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstnamereal -->
        <test-method signature="ph_numberchar()[pri:10, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:01:57Z" name="ph_numberchar" finished-at="2019-02-06T13:02:00Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2660" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [please enter phone number with 10 digit ] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [please enter phone number with 10 digit ] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at src.Wfs_automation.ph_numberchar(Wfs_automation.java:234)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ph_numberchar -->
        <test-method signature="ph_numberspecialchar()[pri:11, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:00Z" name="ph_numberspecialchar" finished-at="2019-02-06T13:02:02Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2520" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [please enter phone number with 10 digit ] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [please enter phone number with 10 digit ] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at src.Wfs_automation.ph_numberspecialchar(Wfs_automation.java:256)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ph_numberspecialchar -->
        <test-method signature="ph_numberless()[pri:12, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:02Z" name="ph_numberless" finished-at="2019-02-06T13:02:04Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2437" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [please enter phone number with 10 digit ] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [please enter phone number with 10 digit ] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at src.Wfs_automation.ph_numberless(Wfs_automation.java:278)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ph_numberless -->
        <test-method signature="ph_numbermore()[pri:13, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:04Z" name="ph_numbermore" finished-at="2019-02-06T13:02:07Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2584" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [please enter phone number with 10 digit ] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [please enter phone number with 10 digit ] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at src.Wfs_automation.ph_numbermore(Wfs_automation.java:300)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ph_numbermore -->
        <test-method signature="ph_numbermix()[pri:14, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:07Z" name="ph_numbermix" finished-at="2019-02-06T13:02:10Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2539" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [please enter phone number with 10 digit ] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [please enter phone number with 10 digit ] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at src.Wfs_automation.ph_numbermix(Wfs_automation.java:323)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ph_numbermix -->
        <test-method signature="ph_number_real()[pri:15, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:10Z" name="ph_number_real" finished-at="2019-02-06T13:02:12Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2372" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ph_number_real -->
        <test-method signature="email()[pri:16, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:12Z" name="email" finished-at="2019-02-06T13:02:15Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2522" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- email -->
        <test-method signature="email_dot()[pri:17, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:15Z" name="email_dot" finished-at="2019-02-06T13:02:17Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2430" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- email_dot -->
        <test-method signature="email_specialsymbol()[pri:18, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:17Z" name="email_specialsymbol" finished-at="2019-02-06T13:02:19Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2475" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- email_specialsymbol -->
        <test-method signature="email_int()[pri:19, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:19Z" name="email_int" finished-at="2019-02-06T13:02:22Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2390" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- email_int -->
        <test-method signature="email_real()[pri:20, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:22Z" name="email_real" finished-at="2019-02-06T13:02:24Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- email_real -->
        <test-method signature="password()[pri:21, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:24Z" name="password" finished-at="2019-02-06T13:02:27Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2492" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- password -->
        <test-method signature="password_alpha()[pri:22, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:27Z" name="password_alpha" finished-at="2019-02-06T13:02:29Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2325" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- password_alpha -->
        <test-method signature="password_mix()[pri:23, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:29Z" name="password_mix" finished-at="2019-02-06T13:02:32Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2399" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please enter 8 digit password with character and integer] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please enter 8 digit password with character and integer] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at src.Wfs_automation.password_mix(Wfs_automation.java:495)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- password_mix -->
        <test-method signature="password_i()[pri:24, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:32Z" name="password_i" finished-at="2019-02-06T13:02:34Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2449" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please enter 8 digit password with character and integer] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please enter 8 digit password with character and integer] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at src.Wfs_automation.password_i(Wfs_automation.java:513)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- password_i -->
        <test-method signature="password_real()[pri:25, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:34Z" name="password_real" finished-at="2019-02-06T13:02:36Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2338" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- password_real -->
        <test-method signature="confirm_password()[pri:26, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:36Z" name="confirm_password" finished-at="2019-02-06T13:02:39Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2469" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirm_password -->
        <test-method signature="confirm_password_int()[pri:27, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:39Z" name="confirm_password_int" finished-at="2019-02-06T13:02:41Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2493" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirm_password_int -->
        <test-method signature="confirm_password_i()[pri:28, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:41Z" name="confirm_password_i" finished-at="2019-02-06T13:02:44Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2382" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirm_password_i -->
        <test-method signature="confirm_password_8()[pri:29, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:44Z" name="confirm_password_8" finished-at="2019-02-06T13:02:46Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirm_password_8 -->
        <test-method signature="confirm_password_real()[pri:30, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:46Z" name="confirm_password_real" finished-at="2019-02-06T13:02:49Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="2397" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirm_password_real -->
        <test-method signature="checkbox()[pri:31, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:49Z" name="checkbox" finished-at="2019-02-06T13:02:57Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="8456" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkbox -->
        <test-method signature="yopmail()[pri:32, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:02:57Z" name="yopmail" finished-at="2019-02-06T13:03:57Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="59865" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- yopmail -->
        <test-method signature="admin()[pri:33, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:03:57Z" name="admin" finished-at="2019-02-06T13:03:58Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="958" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- admin -->
        <test-method signature="department()[pri:34, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:03:58Z" name="department" finished-at="2019-02-06T13:04:03Z" depends-on-methods="src.Wfs_automation.checkvalidation" duration-ms="5187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- department -->
        <test-method signature="department_submit()[pri:35, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:04:03Z" name="department_submit" finished-at="2019-02-06T13:04:04Z" depends-on-methods="src.Wfs_automation.department" duration-ms="465" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- department_submit -->
        <test-method signature="department_name()[pri:36, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:04:04Z" name="department_name" finished-at="2019-02-06T13:04:06Z" depends-on-methods="src.Wfs_automation.department" duration-ms="2696" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- department_name -->
        <test-method signature="departmenttcode()[pri:37, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:04:06Z" name="departmenttcode" finished-at="2019-02-06T13:04:09Z" depends-on-methods="src.Wfs_automation.department" duration-ms="2716" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- departmenttcode -->
        <test-method signature="dept_real()[pri:38, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:04:09Z" name="dept_real" finished-at="2019-02-06T13:04:16Z" depends-on-methods="src.Wfs_automation.department" duration-ms="7346" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dept_real -->
        <test-method signature="dept_edit()[pri:39, instance:src.Wfs_automation@6ab778a]" started-at="2019-02-06T13:04:16Z" name="dept_edit" finished-at="2019-02-06T13:04:29Z" depends-on-methods="src.Wfs_automation.department" duration-ms="12170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dept_edit -->
      </class> <!-- src.Wfs_automation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
